language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
sudo: false
install:
  - pip install tox python-coveralls
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_success:
  - coverage report && coveralls
